import type { Product, Category, Banner } from "./types";

export const categories: Category[] = [
  { id: "fruits", name: "Fruits", image: "https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=300", color: "#FFE5E5" },
  { id: "veggies", name: "Vegetables", image: "https://images.pexels.com/photos/1656664/pexels-photo-1656664.jpeg?auto=compress&cs=tinysrgb&w=300", color: "#E5F5E5" },
  { id: "dairy", name: "Dairy & Eggs", image: "https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=300", color: "#FFF9E5" },
  { id: "snacks", name: "Snacks", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-Q3Il2CTqOPWWO46lY0GE5f1YHYUGJKyODzVeMgbe8Q&s=10", color: "#FFF0E5" },
  { id: "beverages", name: "Beverages", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx9oPOAKQrWOVnutzvtiy_kBnZ-sNQSPG6BgYbwNK3eQ&s", color: "#E5F0FF" },
  { id: "bakery", name: "Bakery", image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=300", color: "#F5E5FF" },
  { id: "icecream", name: "Ice Cream", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQytu0ubfJMzqm7sLcPZJRNEr09vIXdUhLANc2fkQIYsg&s=10", color: "#E5F5FF" },
  { id: "personal", name: "Personal Care", image: "https://images.pexels.com/photos/4202325/pexels-photo-4202325.jpeg?auto=compress&cs=tinysrgb&w=300", color: "#E5FFF5" },
  { id: "cleaning", name: "Cleaning", image: "https://images.pexels.com/photos/4108715/pexels-photo-4108715.jpeg?auto=compress&cs=tinysrgb&w=300", color: "#FFFFE5" },
  { id: "staples", name: "Staples", image: "https://images.pexels.com/photos/533325/pexels-photo-533325.jpeg?auto=compress&cs=tinysrgb&w=300", color: "#F5E5E0" },
  { id: "baby", name: "Baby Care", image: "https://images.pexels.com/photos/265982/pexels-photo-265982.jpeg?auto=compress&cs=tinysrgb&w=300", color: "#FFE5F0" },
  { id: "pets", name: "Pet Supplies", image: "https://images.pexels.com/photos/4587955/pexels-photo-4587955.jpeg?auto=compress&cs=tinysrgb&w=300", color: "#E5E5FF" },
];

export const banners: Banner[] = [
  {
    id: "b1",
    title: "Get 10% Cashback",
    subtitle: "On orders above ₹500 with Zepto Cash",
    image: "https://images.pexels.com/photos/4393818/pexels-photo-4393818.jpeg?auto=compress&cs=tinysrgb&w=800",
    bgColor: "#950EDB",
  },
  {
    id: "b2",
    title: "Fresh Fruits & Veggies",
    subtitle: "Farm fresh, delivered in 10 minutes",
    image: "https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=800",
    bgColor: "#0C831F",
  },
  {
    id: "b3",
    title: "Snack Attack Sale",
    subtitle: "Up to 50% off on your favorite snacks",
    image: "https://images.pexels.com/photos/8877037/pexels-photo-8877037.jpeg?auto=compress&cs=tinysrgb&w=800",
    bgColor: "#F5C518",
  },
  {
    id: "b4",
    title: "Zepto Pass",
    subtitle: "Free delivery on all orders above ₹99",
    image: "https://images.pexels.com/photos/4393426/pexels-photo-4393426.jpeg?auto=compress&cs=tinysrgb&w=800",
    bgColor: "#7A0CB8",
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Fresh Bananas - Robusta",
    image: "https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: 49, mrp: 70, unit: "1 kg", rating: 4.2, ratingCount: "12.3k",
    category: "fruits", tags: ["Bestseller"],
    description: "Fresh, ripe robusta bananas. Rich in potassium and perfect for a quick snack or smoothie.",
  },
  {
    id: "p2",
    name: "Royal Gala Apples",
    image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: 189, mrp: 240, unit: "1 kg", rating: 4.5, ratingCount: "8.7k",
    category: "fruits", tags: ["Bestseller"],
    description: "Premium Royal Gala apples. Sweet, crisp and juicy. Perfect for snacking or baking.",
  },
  {
    id: "p3",
    name: "Fresh Tomatoes",
    image: "https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: 29, mrp: 45, unit: "500 g", rating: 4.0, ratingCount: "15.2k",
    category: "veggies", tags: [],
    description: "Farm-fresh red tomatoes. Great for curries, salads, and sauces.",
  },
  {
    id: "p4",
    name: "Onions - Fresh",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKH-VRTuXPWlEpjgnLpSRiRpHLGQo-IFW1zbWxy--gtg&s=10",
    price: 35, mrp: 50, unit: "1 kg", rating: 4.1, ratingCount: "9.1k",
    category: "veggies", tags: ["Bestseller"],
    description: "Fresh, firm onions. An essential kitchen staple for everyday cooking.",
  },
  {
    id: "p5",
    name: "Amul Gold Full Cream Milk",
    image: "https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: 33, mrp: 35, unit: "500 ml", rating: 4.7, ratingCount: "41.7k",
    category: "dairy", tags: ["Bestseller"],
    description: "Amul Gold full cream milk. Rich and creamy, perfect for tea, coffee, and sweets.",
  },
  {
    id: "p6",
    name: "Farm Fresh Eggs - Pack of 6",
    image: "https://images.pexels.com/photos/162712/egg-white-food-protein-162712.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: 72, mrp: 90, unit: "6 pcs", rating: 4.6, ratingCount: "22.1k",
    category: "dairy", tags: ["Bestseller"],
    description: "Farm fresh brown eggs. Rich in protein, perfect for breakfast and baking.",
  },
  {
    id: "p7",
    name: "Lay's Classic Salted Chips",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTds-45JlpVr4QSWK4z039Q4nhrvWwTcJIG2Er8G6d9OQ&s=10",
    price: 20, mrp: 30, unit: "52 g", rating: 4.4, ratingCount: "31.5k",
    category: "snacks", tags: ["Bestseller"],
    description: "Crispy, crunchy Lay's Classic Salted potato chips. The perfect anytime snack.",
  },
  {
    id: "p8",
    name: "Kurkure Masala Munch",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVoVk2Xk6vVlIIuLiwuYmmfU1iK19x67zgzf8vh6ax-Q&s=10",
    price: 20, mrp: 25, unit: "90 g", rating: 4.3, ratingCount: "18.9k",
    category: "snacks", tags: [],
    description: "Crunchy corn puffs with tangy masala flavor. A beloved Indian snack.",
  },
  {
    id: "p9",
    name: "Coca-Cola - PET Bottle",
    image: "https://images.pexels.com/photos/2983100/pexels-photo-2983100.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: 40, mrp: 65, unit: "750 ml", rating: 4.6, ratingCount: "27.3k",
    category: "beverages", tags: ["Bestseller"],
    description: "Refreshing Coca-Cola in a convenient PET bottle. Best served chilled.",
  },
  {
    id: "p10",
    name: "Tropicana Orange Juice",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGIhwU_-zPntLSZsGmbvIuMxALxlQiwjkK_DH8V3E2oA&s=10",
    price: 99, mrp: 120, unit: "1 L", rating: 4.5, ratingCount: "14.2k",
    category: "beverages", tags: [],
    description: "100% orange juice from Tropicana. No added preservatives, full of vitamin C.",
  },
  {
    id: "p11",
    name: "Fresh Bread - White",
    image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: 40, mrp: 50, unit: "400 g", rating: 4.3, ratingCount: "11.8k",
    category: "bakery", tags: ["Bestseller"],
    description: "Soft, fresh white bread. Perfect for sandwiches, toast, and more.",
  },
  {
    id: "p12",
    name: "Croissant - Butter",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd0GpCdyROuC-Hol9ufCTurumBzU184K0MX8gggjYuDQ&s=10",
    price: 75, mrp: 99, unit: "2 pcs", rating: 4.7, ratingCount: "5.4k",
    category: "bakery", tags: [],
    description: "Flaky, buttery croissants baked fresh. A perfect breakfast treat.",
  },
  {
    id: "p13",
    name: "Amul Ice Cream - Vanilla",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9yKlas2cO5q4enoXm7J3UNgTkACZQWpkW9dzNA68GsA&s=10",
    price: 99, mrp: 130, unit: "700 ml", rating: 4.8, ratingCount: "19.6k",
    category: "icecream", tags: ["Bestseller"],
    description: "Creamy vanilla ice cream from Amul. Classic flavor loved by all ages.",
  },
  {
    id: "p14",
    name: "Chocolate Ice Cream Tub",
    image: "https://images.pexels.com/photos/1352284/pexels-photo-1352284.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: 199, mrp: 250, unit: "1 L", rating: 4.7, ratingCount: "8.9k",
    category: "icecream", tags: [],
    description: "Rich, creamy chocolate ice cream. Made with real cocoa for deep flavor.",
  },
  {
    id: "p15",
    name: "Dove Shampoo - Daily Moisture",
    image: "https://images.pexels.com/photos/4202325/pexels-photo-4202325.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: 175, mrp: 220, unit: "340 ml", rating: 4.5, ratingCount: "7.2k",
    category: "personal", tags: [],
    description: "Dove Daily Moisture shampoo. Nourishes hair for soft, smooth results.",
  },
  {
    id: "p16",
    name: "Colgate Toothpaste - MaxFresh",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPAcNJ2BAWMJ8hAFnUkgjzv07_U3OpnwLdbV9miq-yLA&s=10",
    price: 89, mrp: 120, unit: "150 g", rating: 4.4, ratingCount: "16.3k",
    category: "personal", tags: ["Bestseller"],
    description: "Colgate MaxFresh toothpaste with cooling crystals for long-lasting fresh breath.",
  },
  {
    id: "p17",
    name: "Surf Excel Detergent - Front Load",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6y1uJGP_tPPEG9Q1QrhG2by9Vvt2d9W0Xr3g6mIjvww&s=10",
    price: 224, mrp: 260, unit: "2 kg", rating: 4.8, ratingCount: "41.7k",
    category: "cleaning", tags: ["Bestseller"],
    description: "Surf Excel Matic front load detergent liquid. Tough on stains, gentle on clothes.",
  },
  {
    id: "p18",
    name: "Harpic Toilet Cleaner - Lime",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc5P2PIXC7jz3IYyotd3Z4Jf4F04IUAKqcWRgY6aXjSQ&s",
    price: 85, mrp: 99, unit: "1 L", rating: 4.5, ratingCount: "12.4k",
    category: "cleaning", tags: [],
    description: "Harpic Lime Fresh toilet cleaner. Kills 99.9% germs and leaves a fresh scent.",
  },
  {
    id: "p19",
    name: "India Gate Basmati Rice - Premium",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQIJ2RDzAJY63-33wvIhhjmslYpjyVHMuuIDxM_vQ9mg&s=10",
    price: 145, mrp: 180, unit: "1 kg", rating: 4.6, ratingCount: "23.8k",
    category: "staples", tags: ["Bestseller"],
    description: "India Gate premium basmati rice. Long grain, aromatic, and perfect for biryani.",
  },
  {
    id: "p20",
    name: "Tata Salt - Iodized",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBvlNVrWpl08ogMFZoPqN_Mu3TXTZdinkDQuOtJL6ahQ&s=10",
    price: 28, mrp: 35, unit: "1 kg", rating: 4.7, ratingCount: "35.1k",
    category: "staples", tags: ["Bestseller"],
    description: "Tata Salt iodized table salt. India's trusted salt brand for daily cooking.",
  },
  {
    id: "p21",
    name: "Pampers Baby Diapers - Medium",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlJMvRUnuYbmIse8FqcQekG72q1UQZfp99wLn93GaafA&s=10",
    price: 599, mrp: 799, unit: "62 pcs", rating: 4.6, ratingCount: "9.8k",
    category: "baby", tags: ["Bestseller"],
    description: "Pampers baby dry diapers. Up to 12 hours of dryness for your baby's comfort.",
  },
  {
    id: "p22",
    name: "Mangoes - Alphonso",
    image: "https://images.pexels.com/photos/2294471/pexels-photo-2294471.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: 499, mrp: 650, unit: "1 dozen", rating: 4.8, ratingCount: "6.7k",
    category: "fruits", tags: ["Bestseller"],
    description: "Premium Alphonso mangoes. The king of fruits — sweet, aromatic, and juicy.",
  },
  {
    id: "p23",
    name: "Green Capsicum - Bell Pepper",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8CwkcwP5Pia9el0zobw9ISD3KgqqIGQ1dDZlqOcM3_w&s=10",
    price: 45, mrp: 65, unit: "250 g", rating: 4.2, ratingCount: "4.3k",
    category: "veggies", tags: [],
    description: "Fresh green bell peppers. Crunchy and sweet, great for salads and stir-fries.",
  },
  {
    id: "p24",
    name: "Red Bull Energy Drink",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnHcCJ8dsYZU3JWl-fPVaRCfHMkKWZvRkS3ug9cHPeew&s=10",
    price: 125, mrp: 150, unit: "250 ml", rating: 4.5, ratingCount: "13.2k",
    category: "beverages", tags: [],
    description: "Red Bull energy drink. Gives you wings — vitalizes body and mind.",
  },
  {
    id: "p25",
    name: "Muntain Dew",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCBWqgDN7LOnEHWR0-SrpufESsGJVJeCttAqhyrS1iDA&s=10",
    price: 65, mrp: 80, unit: "100 ml", rating: 4.5, ratingCount: "19.4k",
    category: "beverages", tags: ["Bestseller"],
    description: "Mountain Dew - Dar ke Aage Jeet Haii",
  },
  {
    id: "p26",
    name: "Pineapple - Indian",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKDexQxKgcCsLpmR29EcZinroiT5Mx-SppeHxiFdPg9Q&s=10",
    price: 49, mrp: 60, unit: "1 peice", rating: 4.8, ratingCount: "6.7k",
    category: "fruits", tags: ["Bestseller"],
    description: "Premium Pineapple. The son of fruits — sweet, aromatic, and juicy.",
  },
  {
    id: "p27",
    name: "Cocktail - Retro",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDW-aq3JyyJTP08z1BOceffhOflR55lTH4LdCNmIKTgQ&s=10",
    price: 115, mrp: 180, unit: "150 ml", rating: 4.2, ratingCount: "1.4k",
    category: "beverages", tags: [],
    description: "Retro - cocktails. The revival of your cold version deadly summer",
  },
  {
    id: "p28",
    name: "Maaza - The freshness of mangoes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVf6i1QT0OwvAYpyL3uos664fz-LJHDiD20VUs2CNE0g&s=10",
    price: 65, mrp: 100, unit: "150 ml", rating: 4.2, ratingCount: "21.4k",
    category: "beverages", tags: [],
    description: "Maaza. The freshness of fresh mangoes to reach your soul",
  },
  {
    id: "p29",
    name: "Coca-Cola - PET Bottle",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfb2_hpY9I9BlxH3SOS1pThQoyH7Q3L-vHN9JaGfbARg&s=10",
    price: 60, mrp: 65, unit: "750 ml", rating: 4.6, ratingCount: "27.3k",
    category: "beverages", tags: ["Bestseller"],
    description: "Refreshing Coca-Cola in a convenient PET bottle. Best served chilled.",
  },
  {
    id: "p30",
    name: "Amul Masti Dahi",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRED5D1-SqKKASyJnkddNjag7FBuvtxp1bAP8y4T6IPGQ&s=10",
    price: 45,
    mrp: 72,
    unit: "1.5 L",
    rating: 4.8,
    ratingCount: "12.4k",
    category: "dairy",
    tags: ["Bestseller"],
    description: "Fresh full cream dahi rich in calcium and protein. Perfect for daily consumption.",
  },
  {
    id: "p31",
    name: "Fresh Amul Paneer",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjZzS_tDdyz8G-VFPgwpgHcivO1d2_ocuqUO-tHqDfYg&s=10",
    price: 84,
    mrp: 90,
    unit: "6 pcs",
    rating: 4.7,
    ratingCount: "8.9k",
    category: "dairy",
    tags: ["Fresh"],
    description: "Creamy salted paneer made from fresh milk, ideal for bread, sandwiches, and cooking.",
  },
  {
    id: "p32",
    name: "Amul Salted Butter",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD1F7A2I_-bHQS-hqGWZO8naq1xwBUJg1zFMut3r8A_g&s=10",
    price: 62,
    mrp: 65,
    unit: "100 g",
    rating: 4.9,
    ratingCount: "15.3k",
    category: "dairy",
    tags: ["Popular"],
    description: "Creamy salted butter made from fresh milk, ideal for bread, sandwiches, and cooking.",
  },
  {
    id: "p33",
    name: "Washington Apples",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRn0ZLld2E0ZHH83eyIomStrYvwr8TsS_ekC1GPlPizzQ&s=10",
    price: 199,
    mrp: 220,
    unit: "1 kg",
    rating: 4.7,
    ratingCount: "7.3k",
    category: "fruits",
    tags: ["Apple", "Fresh", "Premium"],
    description: "Premium Washington apples with a crisp texture and naturally sweet flavor."
  },
  {
    id: "p34",
    name: "Fresh Oranges",
    image: "https://5.imimg.com/data5/SELLER/Default/2024/5/419942629/KP/TV/EV/184025675/fresh-orange-fruit-500x500.png",
    price: 89,
    mrp: 99,
    unit: "1 kg",
    rating: 4.6,
    ratingCount: "5.8k",
    category: "fruits",
    tags: ["Orange", "Citrus", "Vitamin C"],
    description: "Juicy oranges packed with Vitamin C to keep you refreshed and healthy."
  },
  {
    id: "p35",
    name: "Seedless Green Grapes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2IrsZbg2ltIhEyBfhlTj1LVKN-iFoZhTJ06V24K271w&s=10",
    price: 129,
    mrp: 149,
    unit: "500 g",
    rating: 4.5,
    ratingCount: "4.2k",
    category: "fruits",
    tags: ["Grapes", "Seedless", "Fresh"],
    description: "Sweet and seedless green grapes, carefully selected for freshness and taste."
  },
  {
    id: 'p36',
    name: "Fresh Pomegranate",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrjoXyM2crpwiNI4kDCz0mQCtka-UmGlEWJtKOS5PkrA&s=10",
    price: 179,
    mrp: 195,
    unit: "1 kg",
    rating: 4.8,
    ratingCount: "6.5k",
    category: "fruits",
    tags: ["Pomegranate", "Antioxidants", "Fresh"],
    description: "Fresh pomegranates with juicy ruby-red arils, rich in antioxidants and nutrients."
  },
  {
    id: 'p37',
    name: "Sous Vide Chocolate Icecream",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7TitSgH8nkyaG5bzK_p6cUjlqbjkC-GLNWaf9FQgTug&s=10",
    price: 199,
    mrp: 230,
    unit: "700 ml",
    rating: 4.8,
    ratingCount: "19.6k",
    category: "icecream",
    tags: ["Bestseller"],
    description: "Creamy vanilla ice cream from Amul. A classic flavor loved by all ages."
  },
  {
    id: 'p38',
    name: "Kwality Wall's Magnum Almond",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVT6pt0unOFqAuypE5UHHAFx_eG3guhw6G-DB0KuwzGQ&s",
    price: 95,
    mrp: 110,
    unit: "80 ml",
    rating: 4.9,
    ratingCount: "14.2k",
    category: "icecream",
    tags: ["Premium"],
    description: "Rich vanilla ice cream coated with Belgian chocolate and crunchy almonds."
  },
  {
    id: 'p39',
    name: "Double Dutch Dark Chocolate Icecream",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpG62XL4A6I6NBKR25zPLo_G7tLyjt9hdYm46xUDqHrw&s=10",
    price: 120,
    mrp: 145,
    unit: "700 ml",
    rating: 4.7,
    ratingCount: "11.8k",
    category: "icecream",
    tags: ["Chocolate"],
    description: "Smooth and creamy dark chocolate ice cream made with rich cocoa for a delicious dessert."
  },
  {
    id: "p40",
    name: "Amul Full Cream Milk",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsf8JOsWsNGwyqdCy4DTJwqU0jbhSMO5RBWp6wDAngug&s=10",
    price: 33, mrp: 35, unit: "500 ml", rating: 4.7, ratingCount: "41.7k",
    category: "dairy", tags: ["Bestseller"],
    description: "Amul Gold full cream milk. Rich and creamy, perfect for tea, coffee, and sweets.",
  },
];

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getBestsellers(): Product[] {
  return products.filter((p) => p.tags.includes("Bestseller"));
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) => p.name.toLowerCase().includes(q) || p.category.toLowerCase().includes(q)
  );
}
